# Generated by Django 5.1.4 on 2024-12-24 20:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Title')),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('idtour', models.IntegerField(blank=True, null=True)),
                ('firstdistination', models.CharField(blank=True, max_length=50, null=True)),
                ('lastDestination', models.CharField(blank=True, max_length=50, null=True)),
                ('startdate', models.DateField(blank=True, null=True)),
                ('finishdate', models.DateField(blank=True, null=True)),
                ('capacity', models.IntegerField(blank=True, default=20000, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('image', models.ImageField(blank=True, null=True, upload_to='tour/')),
                ('ticket_type', models.CharField(choices=[('bus', 'اتوبوس'), ('train', 'قطار')], default='bus', max_length=10)),
                ('clas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tour_clas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_purchases', to=settings.AUTH_USER_MODEL)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_purchases', to='tour.tour')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tour_profile', to=settings.AUTH_USER_MODEL)),
                ('tours', models.ManyToManyField(blank=True, related_name='tour_profiles', to='tour.tour')),
            ],
        ),
    ]
