# Generated by Django 5.1.4 on 2024-12-25 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0002_alter_tour_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='description',
        ),
    ]
