# Generated by Django 5.1.6 on 2025-03-30 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0003_remove_tour_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='price',
            field=models.PositiveIntegerField(default=1000, verbose_name='قیمت'),
        ),
    ]
