# Generated by Django 5.1.6 on 2025-04-05 04:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0004_tour_price'),
        ('tourism', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tourisms',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='tourism.tourism'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tours',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='tour.tour'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
