# Generated by Django 5.1.6 on 2025-04-05 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='is_verified',
            field=models.BooleanField(default=None, null=True, verbose_name='تأیید شده'),
        ),
    ]
