# Generated by Django 5.1.4 on 2024-12-29 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='house',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_house', models.CharField(blank=True, max_length=100, null=True, verbose_name='Title')),
                ('description_house', models.TextField(blank=True, null=True)),
                ('image_house', models.ImageField(blank=True, null=True, upload_to='tourr/')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_accommodations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
